spring.application.name=shopsphere-order-service

server.port=8085

## PostgreSQL
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere_order_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

## Init DB
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:sql/initiate.sql,classpath:sql/sample_records.sql
# spring.sql.init.data-locations=classpath:sql/initiate.sql

## Logging level
# logging.level.org.springframework.web=DEBUG

## Oauth2 Resource Server JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8087/.well-known/jwks.json

## Service-to-Service Authentication (Client Credentials)
service.auth.client-id=${SERVICE_CLIENT_ID:order-service}
service.auth.client-secret=${SERVICE_CLIENT_SECRET}
service.auth.token-uri=http://localhost:8087/api/auth/token

## Kafka Properties
kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic.order-placed=${KAFKA_ORDER_PLACED_TOPIC:order-placed-events}
